# This is a common .travis.yml for generating library release zip files for
# CircuitPython library releases using circuitpython-build-tools.
# See https://github.com/adafruit/circuitpython-build-tools for detailed setup
# instructions.

dist: xenial
language: python
python:
  - "3.6"

cache:
  pip: true

# TODO: if deployment to PyPi is desired, change 'DEPLOY_PYPI' to "true",
#       or remove the env block entirely and remove the condition in the
#       deploy block.
env:
  - DEPLOY_PYPI="true"

deploy:
  - provider: releases
    api_key: "$GITHUB_TOKEN"
    file_glob: true
    file: "$TRAVIS_BUILD_DIR/bundles/*"
    skip_cleanup: true
    overwrite: true
    on:
      tags: true
  # TODO: Use 'travis encrypt --com -r adafruit/<repo slug>' to generate
  #       the encrypted password for adafruit-travis. Paste result below.
  - provider: pypi
    user: adafruit-travis
    password:
      secure: crio5tSRfYyiic1693xoBkllXo4WnVocepQEED2+41EoF403h26h8Sn1WNwgiZP5pfBH9EFkOhvvkh2N0inOCrsaBhpWIBp44dd6NgyrW8K8UK02lAJ0yEyzA54mWPgi0B7g93R9tZXJfiq/csQLnZuu95EITzvM8+7TwtzlidM7Ajq3wXZYeRjnznjsiStqSA+dk8FjN3br4+8aE46F0MJ7fYg/Fw75Cr2GrFCsMPFqGVRvWb4zQq0NBFCxTi67FT82cMwOwLUzNU9jI9hGMDobwzyzJAubj808oZaQ9nG57ixKRElz9gT0W5J90/C1My9OH/T76aWemJHRaqTIOITYvjwvS4RmDkNg49wkv6+B/egt86n7ASTLKtXxpx1cxNH2BV7zDj3Gn2Ng10KTKUKPYtOvMWkAJju+OLAksQphp+7ABnfQf+SelNyPI84HHG4L0eITiWKr25ZSkBzUpHseBJlR77EBTjdJqWD0tQUE6gIXGzRqWz5ySV4QbEND0K4jWldpUtkZMCPplYpqdxZISDpFaTSKeFuoSM/UJ3aC50Og+DHXKvezr9H+r+OSJy+1WofQyvth8rPC77fG6lzdEd8mjXpp3ogptbtsZedQpRCZKSr1xn9Said3n8eW4OZlYMYvxiBlhxFX7xW/RrZqOkExQJ4EUGvEcO4NSX0=
    on:
      tags: true
      condition: $DEPLOY_PYPI = "true"

install:
  - pip install -r requirements.txt
  - pip install circuitpython-build-tools Sphinx sphinx-rtd-theme
  - pip install --force-reinstall pylint==1.9.2

script:
  - pylint adafruit_ds3502.py
  - ([[ ! -d "examples" ]] || pylint --disable=missing-docstring,invalid-name,bad-whitespace examples/*.py)
  - circuitpython-build-bundles --filename_prefix adafruit-circuitpython-ds3502 --library_location .
  - cd docs && sphinx-build -E -W -b html . _build/html && cd ..
